import { existsSync, readFileSync } from 'node:fs';
import { sourceInventory, formulas, englishOutline, aiPracticeBank, officialQuestions, sampleQuestion } from '../src/data.js';
import { cleanText, isSolutionTitle, parseCorrectAnswerHeader, splitSolutionBlocks } from '../scripts/parse-official-content.js';

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

const html = readFileSync('index.html', 'utf8');
const notFoundHtml = readFileSync('404.html', 'utf8');
const app = readFileSync('src/app.js', 'utf8');
const pagesWorkflow = readFileSync('.github/workflows/deploy-pages.yml', 'utf8');
const bulkIngestWorkflow = readFileSync('.github/workflows/bulk-ingest-campus-pdfs.yml', 'utf8');
const discoverScript = readFileSync('scripts/discover-pdfs.js', 'utf8');
const parserScript = readFileSync('scripts/parse-official-content.js', 'utf8');
const artifactParser = readFileSync('src/artifactParser.js', 'utf8');
const docsHtml = readFileSync('docs/index.html', 'utf8');
const docsApp = readFileSync('docs/src/app.js', 'utf8');
const sourceManifest = JSON.parse(readFileSync('data/sources/campus-il-pdfs.json', 'utf8'));
const pdfMetadata = JSON.parse(readFileSync('data/extracted/pdfs/metadata.json', 'utf8'));
const extractedFormulas = JSON.parse(readFileSync('data/extracted/formulas/quant-summary-formulas.json', 'utf8'));
const officialIndex = JSON.parse(readFileSync('data/official/content-index.json', 'utf8'));

assert(html.includes('lang="he"'), 'index.html must declare Hebrew language');
assert(html.includes('dir="rtl"'), 'index.html must declare RTL direction');
assert(notFoundHtml.includes('src/app.js'), '404.html must load the app for GitHub Pages fallback routes');
assert(docsHtml.includes('src/app.js'), 'docs/index.html must support branch-based GitHub Pages from /docs');
assert(docsApp.includes('שאלה זו נוצרה על ידי AI'), 'docs app mirror must include the AI disclaimer');
assert(app.includes('שאלה זו נוצרה על ידי AI'), 'AI-generated questions must include a clear disclaimer');
assert(app.includes('ספריית PDF רשמית'), 'app must expose the official PDF library');
assert(app.includes('אינדקס תוכן מכל ה־PDFים'), 'app must expose the all-PDF content index');
assert(app.includes('loadArtifactExplanations'), 'app must load existing artifact explanations without rerunning ingest');
assert(app.includes('בלי להריץ שוב Bulk ingest'), 'app must explain that existing artifacts can be reused');
assert(app.includes('טען הסברים מכל קובצי הפתרונות'), 'app must load all solution PDFs from existing artifacts at once');
assert(!app.includes('slice(0, 6)'), 'artifact loader must not limit extraction to the first six solution PDFs');
assert(app.includes('<iframe'), 'app must embed selected official PDFs for reading');
assert(app.includes('חזרה על טעויות'), 'app must include review mode');
assert(app.includes('localStorage'), 'app must persist user progress locally');
assert(app.includes('איפוס התקדמות'), 'app must include dashboard progress controls');
assert(sourceInventory.length >= 4, 'source inventory should include initial Campus IL PDF sources');
assert(sourceInventory.every((source) => source.url.includes('courses.campus.gov.il') && source.type === 'PDF'), 'all source URLs must be Campus IL PDFs');
assert(sourceInventory.every((source) => Number.isInteger(source.pageCount) && source.pageCount > 0), 'app sources need extracted page counts');
assert(formulas.length >= 12, 'formula sheet should contain meaningful study content, not just placeholders');
assert(formulas.every((formula) => formula.sourceTitle && formula.page && formula.reviewStatus && formula.example), 'formulas need source metadata, review status, and examples');
assert(englishOutline.length > 0 && englishOutline.every((section) => section.page && section.items.length), 'English outline must include page-backed items');
assert(aiPracticeBank.length >= 3, 'AI practice bank should include labeled practice questions');
assert(officialQuestions.length >= 17, 'app must include extracted official Campus IL questions from multiple PDFs');
assert(new Set(officialQuestions.map((q) => q.source.title)).has('פתרונות סימולציה קמפוס 2'), 'official questions must include content from Simulation 2 solutions');
assert(officialQuestions.every((q) => q.sourceType === 'official' && q.source && q.source.url.includes('courses.campus.gov.il') && q.explanation), 'official questions need Campus IL source metadata and explanations');
assert(!sampleQuestion.text.includes('שאלת הדגמה'), 'default practice question must no longer be a skeleton/demo prompt');
assert(sampleQuestion.sourceType === 'official', 'default official question should be marked official');
assert(existsSync('.github/workflows/deploy-pages.yml'), 'GitHub Pages deployment workflow must exist');
assert(existsSync('.nojekyll'), 'GitHub Pages should bypass Jekyll processing');
assert(pagesWorkflow.includes('path: _site'), 'workflow must upload an explicit _site artifact');
assert(pagesWorkflow.includes('cp index.html 404.html .nojekyll _site/'), 'workflow must copy root HTML files into _site');
assert(pagesWorkflow.includes('actions/deploy-pages@v4'), 'workflow must deploy with GitHub Pages action');
assert(bulkIngestWorkflow.includes('npm run discover:pdfs'), 'bulk workflow must discover all PDFs from the downloads page');
assert(bulkIngestWorkflow.includes('poppler-utils'), 'bulk workflow must install PDF text extraction tools');
assert(bulkIngestWorkflow.includes('npm run parse:official'), 'bulk workflow must parse extracted text into structured official datasets');
assert(bulkIngestWorkflow.includes('contents: write'), 'bulk workflow must be able to publish artifacts to a branch');
assert(bulkIngestWorkflow.includes('campus-il-extraction-artifacts'), 'bulk workflow must default to a stable extraction artifact branch');
assert(bulkIngestWorkflow.includes('git push --force origin HEAD:'), 'bulk workflow must force-push generated artifact output without stale lease failures');
assert(bulkIngestWorkflow.includes('generated artifact output'), 'bulk workflow must explain why force push is safe for the artifact branch');
assert(bulkIngestWorkflow.includes('data/official'), 'bulk workflow must publish parsed official artifacts');
assert(parserScript.includes('explanations-preview.json') && parserScript.includes('formula-candidates.json'), 'parser must write explanation and formula artifact files');
assert(artifactParser.includes('splitArtifactSolutions') && artifactParser.includes('cleanArtifactText'), 'browser artifact parser must parse existing extracted text');
assert(isSolutionTitle('פתרונות סימולציה 1'), 'parser must recognize Hebrew solution PDF titles');
assert(parseCorrectAnswerHeader('תשובה (4) נכונה') === 4, 'parser must parse standard Hebrew answer headers');
assert(parseCorrectAnswerHeader('תשובה )4( נכונה') === 4, 'parser must parse reversed parenthesis answer headers');
assert(parseCorrectAnswerHeader('תשובה ) (3 נכונה') === 3, 'parser must parse spaced RTL answer headers');
assert(parseCorrectAnswerHeader('התשובה הנכונה היא (2)') === 2, 'parser must parse alternate correct-answer phrasing');
assert(cleanText('abc\u200f def') === 'abc def', 'parser must remove bidi controls');
assert(splitSolutionBlocks('תשובה (1) נכונה. הסבר ראשון\nתשובה )2( נכונה. הסבר שני').length === 2, 'parser must split multiple solution explanation blocks');
assert(discoverScript.includes('all-campus-il-pdfs.json'), 'discover script must write the all-PDF manifest');
assert(pagesWorkflow.includes('branches: [main]'), 'workflow must deploy pushes to main');
assert(sourceManifest.every((source) => source.url.startsWith('https://courses.campus.gov.il/') && source.url.includes('.pdf')), 'manifest must contain only Campus IL PDFs');
assert(pdfMetadata.length >= 100 && pdfMetadata.every((source) => source.sha256 && source.bytes > 0), 'PDF metadata must include fetched PDF hashes and byte sizes');
assert(officialIndex.pdfCount >= 100 && officialIndex.extractedTextCount >= 100, 'official index must cover the bulk extracted PDFs');
assert(extractedFormulas.every((formula) => formula.sourceId === 'quant-summary' && formula.reviewStatus), 'extracted formulas must remain tied to source and review state');

console.log('כל הבדיקות עברו בהצלחה');
